-- =============================================================================
-- E8 — ai_chat_message
-- Histórico de chat no formato n8n Postgres Chat Memory (LangChain).
-- session_id define o agrupamento da conversa.
-- message jsonb: {"type":"human"|"ai", "content":"...",
--                 "additional_kwargs":{}, "response_metadata":{}}
-- =============================================================================

create table public.ai_chat_message (
  id          bigint generated by default as identity not null,
  session_id  character varying not null,
  message     jsonb null,
  constraint ai_chat_message_pkey primary key (id)
);

-- ============================================================================
-- Fim — E8
-- ============================================================================
